# System Solver

In [1]:
import numpy as np

In [2]:
def row_echelon(A):
    m, n = A.shape
    lead = 0
    for r in range(m):
        if lead >= n:
            break
        i = r
        while A[i, lead] == 0:
            i += 1
            if i == m:
                i = r
                lead += 1
                if n == lead:
                    return A
        A[[i, r]] = A[[r, i]]
        lv = A[r, lead]
        A[r] = A[r] / lv
        for i in range(m):
            if i == r:
                continue
            lv = A[i, lead]
            A[i] = A[i] - lv * A[r]
        lead += 1
    return A

In [18]:
#n = int(input("-number of equations: ")) # number of equations

#A = np.zeros((n, n)) # the scalar matrix
#B = np.zeros(n) # the answers matrix

A = np.array([[3., 2, 4],
              [1, 1, 1],
              [5, 4, 6]])

B = np.array([19, 6, 31])

AB = np.column_stack((A, B)) # augmented matrix

print("A|B = ")
print(AB)

print("-------------")

print("row_echelon(A|B) =")
print(row_echelon(AB))

print("-------------")

print("X = ")
print(row_echelon(AB)[: , 3])

A|B = 
[[ 3.  2.  4. 19.]
 [ 1.  1.  1.  6.]
 [ 5.  4.  6. 31.]]
-------------
row_echelon(A|B) =
[[1. 0. 0. 1.]
 [0. 1. 0. 2.]
 [0. 0. 1. 3.]]
-------------
X = 
[1. 2. 3.]


# Rank of Matrix

In [4]:
C = np.array([[4,0,1],
              [2,0,2],
              [3,0,3]])

m , n = A.shape # dimantions of matrix

#k = np.zeros((m, n)) # the scalar matrix

# find the reduced row echelon form
P = row_echelon(C)
print(P)

# find the rank of matrix
rank = 0

for i in range(len(P)):
    for j in range(len(P[i])):
        if P[i][j] != 0:
            rank += 1 
            break
            
print("rank of matrix is:")
print(rank)

[[1 0 0]
 [0 0 1]
 [0 0 0]]
rank of matrix is:
2


# Eigenvalues (using normal methods)

In [8]:
import sympy as sy

In [17]:
lamda = sy.symbols('lamda')

D = sy.Matrix([[2 , 3, 0, 0],
               [1 , 4, 0, 0],
               [0 , 0, 0, 2],
               [0 , 0, 2, 0]])

p = D.charpoly(lamda); 

#print(p)

print(sy.factor(p))

sy.solve(p,lamda)

PurePoly(lamda**4 - 6*lamda**3 + lamda**2 + 24*lamda - 20, lamda, domain='ZZ')


[-2, 1, 2, 5]